### ISSUE TITLE
Side bars

### ISSUE THREAD

**Issue by newswim** [meteoric/demo#2]
On the demo, it looks like the left and right side navs (?) are always active and could be swiped to. Is this to emulate something like the messenger component on FB? Just curious. Loving this demo so far!

**Comment by nickw** [comment]
I think that's just because we hadn't implemented the concept of active sides yet. Now you can pass `left`, `right`, or `both` to the `sideMenuContainer`: https://github.com/meteoric/meteor-ionic/blob/master/components/ionSideMenuContainer/ionSideMenuContainer.js#L7

**Comment by newswim** [comment]
Cool! I'll try it out :+1:
