### ISSUE TITLE
Error when building for iOS

### ISSUE THREAD

**Issue by andrerfneves** [meteoric/demo#4]
meteor run ios
[[[[[ ~/Code/meteorhunt ]]]]]

=> Started proxy.
=> Started app on iOS Simulator.
=> Started MongoDB.
=> Exited with code: 8
W20150218-15:27:57.584(-5)? (STDERR)            				throw(ex);
W20150218-15:27:57.584(-5)? (STDERR) /Volumes/OSX HD/Users/andreneves/.meteor/packages/meteor-tool/.1.0.40.959pzb++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:173
W20150218-15:27:57.580(-5)? (STDERR)
W20150218-15:27:57.584(-5)? (STDERR)            				      ^
W20150218-15:27:57.584(-5)? (STDERR)     at Accounts.onCreateUser.user.emails (app/server/accounts.js:5:46)
W20150218-15:27:57.584(-5)? (STDERR) TypeError: Cannot read property 'clientId' of undefined
W20150218-15:27:57.585(-5)? (STDERR)     at /Volumes/OSX HD/Users/andreneves/Code/meteorhunt/.meteor/local/build/programs/server/boot.js:212:5
W20150218-15:28:26.508(-5)? (STDERR)
W20150218-15:28:26.510(-5)? (STDERR) /Volumes/OSX HD/Users/andreneves/.meteor/packages/meteor-tool/.1.0.40.959pzb++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:173
W20150218-15:28:26.511(-5)? (STDERR) 						throw(ex);
W20150218-15:28:26.511(-5)? (STDERR) 						      ^
W20150218-15:28:26.511(-5)? (STDERR) TypeError: Cannot read property 'clientId' of undefined
W20150218-15:28:26.511(-5)? (STDERR)     at Accounts.onCreateUser.user.emails (app/server/accounts.js:5:46)
W20150218-15:28:26.511(-5)? (STDERR)     at /Volumes/OSX HD/Users/andreneves/Code/meteorhunt/.meteor/local/build/programs/server/boot.js:212:5
=> Exited with code: 8
   Building the application                  /

![screen shot 2015-02-18 at 3 30 38 pm](https://cloud.githubusercontent.com/assets/2574011/6256080/213906a6-b783-11e4-88b6-175214c11a27.png)

Been trying to run this on iOS simulator. Have been having problems. I just ran it locally on the web, and meteor isn't complaining about Cordova specifics so I'm assuming it doesn't have to do with that. An error code 8 though? Any clues?

Thanks!

**Comment by nickw** [comment]
Looks like you're trying to run [Meteor Hunt](https://github.com/meteoric/meteorhunt) not the demo app? Check the README for that repo, it uses a settings file for the Meteor auth. You'll need to run it like this:

```
meteor run ios --settings settings.json
```

**Comment by andrerfneves** [comment]
Duh. Too many git clones in my Code directory. Mixing meteor apps is not a good idea.
Should work fine now. Cheers @nickw
