### ISSUE TITLE
Errors prevented startup

### ISSUE THREAD

**Issue by dandv** [meteoric/demo#5]
I've just checked out the code and got this error:

```
:~/meteoric$ meteor run
[[[[[ ~/meteoric ]]]]]

=> Started proxy.
=> Started MongoDB.

Changes to your project's package version selections:

meteoric:ionic  downgraded from 0.1.17 to 0.1.16

=> Errors prevented startup:

   While building the application:
   /home/dandv/meteoric/client/stylesheets/app.scss:4:9: Scss compiler error: file to import not found or unreadable:
   .meteor/local/build/programs/server/assets/packages/meteoric_ionic-sass/ionic
   Current dir: /home/dandv/meteoric/client/stylesheets/


=> Your application has errors. Waiting for file change.
```

**Comment by geritol** [comment]
I think if you rerun it everything should work well

**Comment by dandv** [comment]
That's correct, I should've specified it in my first message. Just a hindrance to new users who might not think of running it again.

**Comment by nickw** [comment]
Yeah, definitely a hindrance, but unfortunately out of our control until either Meteor fixes the problem or somebody creates a better SCSS package for Meteor.

**Comment by Poliuk** [comment]
I'm trying to deploy my App to scalingo, as the build fails scalingo doesn't deploys it so the "re run" workaround doesn't work... Any news on this?
