### ISSUE TITLE
Chrome - pop-ups don't show when run from checkout

### ISSUE THREAD

**Issue by dandv** [meteoric/demo#6]
git clone; meteor run, ^C, meteor run

Go to http://localhost:3000/popup in Chrome

Clicking on Show Popup/Confirm/Alert/Prompt doesn't bring them up, even though they work fine in [the demo](http://meteoric.github.io/).

I've tried Chrome 40, then with iPhone 5 selected in DevTools.

**Comment by nickw** [comment]
Check the `meteor-ionic` version in `.meteor/versions`, you're probably running an old version.

**Comment by dandv** [comment]
meteor:ionic was automatically downgraded, ran into that with #5.
