### ISSUE TITLE
No layout when keyboard on

### ISSUE THREAD

**Issue by perusopersonale** [meteoric/demo#8]
Hi, 
I'd like to use meteoric for side project so I start to play with it.
I run demo on my android phone(4.4.2), it works good but and when I try to enter some text 
(user account/form)  I had this behaviour:
![screenshot_2015-03-14-11-00-22](https://cloud.githubusercontent.com/assets/11472323/6651261/f7a1fa76-ca3a-11e4-98f0-e8d899b9de80.png)
![screenshot_2015-03-14-11-01-18](https://cloud.githubusercontent.com/assets/11472323/6651262/f7a68992-ca3a-11e4-858a-fe132f0f1d8d.png)
![screenshot_2015-03-14-11-01-27](https://cloud.githubusercontent.com/assets/11472323/6651263/f7a9c36e-ca3a-11e4-915b-79218d7f7394.png)
![screenshot_2015-03-14-11-01-36](https://cloud.githubusercontent.com/assets/11472323/6651264/f7ab75ec-ca3a-11e4-80b0-122f088ec15b.png)

I create a simple app and have the same issue.
My phone is a low-budget smartphone (LG D320 L70 ).

**Comment by nickw** [comment]
@perusopersonale were you able to figure this out?

**Comment by perusopersonale** [comment]
Yes, thanks.
I follow your suggestion for this: https://github.com/meteoric/meteor-ionic/issues/106
and it works.
