### ISSUE TITLE
Complete component list

### ISSUE THREAD

**Issue by lorensr** [meteoric/demo#9]
This is the closest I see to a component API. Would be nice if it included all of them, eg `ionRadio` is missing.

**Comment by nickw** [comment]
The main repo's README has a list of what has been implemented and what hasn't: https://github.com/meteoric/meteor-ionic#todo

**Comment by lorensr** [comment]
`ionRadio` has already been implemented, it's just not in the demo. I meant it would be nice to either have a demo or API doc that says, "use it like this":

```
{{#ionRadio}}
  content
{{/ionRadio}}
```

and the available args are name, value, and disabled.

**Comment by nickw** [comment]
Ah I see what you mean. Yeah we definitely need some docs. As far as `ionRadio` goes, I mention in the README linked to above that all the form components are implemented through https://github.com/meteoric/autoform-ionic. So there isn't actually an `{{#ionRadio}}` component per se.

**Comment by lorensr** [comment]
Okay, well it's working standalone for me :)

**Comment by nickw** [comment]
Oh ha you're right, I forgot I had started on an `ionRadio` component but abandoned it for autoform: https://github.com/meteoric/meteor-ionic/tree/master/components/ionRadio. Use at your own risk :)
